
import type { EditorThemeClasses } from 'lexical';
import '../styles/main.css';

export const defaultTheme: EditorThemeClasses = {
    autocomplete: 'TypixEditorTheme__autocomplete',
    blockCursor: 'TypixEditorTheme__blockCursor',
    characterLimit: 'TypixEditorTheme__characterLimit',
    code: 'TypixEditorTheme__code',
    codeHighlight: {
        atrule: 'TypixEditorTheme__tokenAttr',
        attr: 'TypixEditorTheme__tokenAttr',
        boolean: 'TypixEditorTheme__tokenProperty',
        builtin: 'TypixEditorTheme__tokenSelector',
        cdata: 'TypixEditorTheme__tokenComment',
        char: 'TypixEditorTheme__tokenSelector',
        class: 'TypixEditorTheme__tokenFunction',
        'class-name': 'TypixEditorTheme__tokenFunction',
        comment: 'TypixEditorTheme__tokenComment',
        constant: 'TypixEditorTheme__tokenProperty',
        deleted: 'TypixEditorTheme__tokenDeleted',
        doctype: 'TypixEditorTheme__tokenComment',
        entity: 'TypixEditorTheme__tokenOperator',
        function: 'TypixEditorTheme__tokenFunction',
        important: 'TypixEditorTheme__tokenVariable',
        inserted: 'TypixEditorTheme__tokenInserted',
        keyword: 'TypixEditorTheme__tokenAttr',
        namespace: 'TypixEditorTheme__tokenVariable',
        number: 'TypixEditorTheme__tokenProperty',
        operator: 'TypixEditorTheme__tokenOperator',
        prolog: 'TypixEditorTheme__tokenComment',
        property: 'TypixEditorTheme__tokenProperty',
        punctuation: 'TypixEditorTheme__tokenPunctuation',
        regex: 'TypixEditorTheme__tokenVariable',
        selector: 'TypixEditorTheme__tokenSelector',
        string: 'TypixEditorTheme__tokenSelector',
        symbol: 'TypixEditorTheme__tokenProperty',
        tag: 'TypixEditorTheme__tokenProperty',
        unchanged: 'TypixEditorTheme__tokenUnchanged',
        url: 'TypixEditorTheme__tokenOperator',
        variable: 'TypixEditorTheme__tokenVariable',
    },
    embedBlock: {
        base: 'TypixEditorTheme__embedBlock',
        focus: 'TypixEditorTheme__embedBlockFocus',
    },
    hashtag: 'TypixEditorTheme__hashtag',
    heading: {
        h1: 'TypixEditorTheme__h1',
        h2: 'TypixEditorTheme__h2',
        h3: 'TypixEditorTheme__h3',
        h4: 'TypixEditorTheme__h4',
        h5: 'TypixEditorTheme__h5',
        h6: 'TypixEditorTheme__h6',
    },
    hr: 'TypixEditorTheme__hr',
    hrSelected: 'TypixEditorTheme__hrSelected',
    image: 'editor-image',
    indent: 'TypixEditorTheme__indent',
    layoutContainer: 'TypixEditorTheme__layoutContainer',
    layoutItem: 'TypixEditorTheme__layoutItem',
    link: 'TypixEditorTheme__link',
    list: {
        checklist: 'TypixEditorTheme__checklist',
        listitem: 'TypixEditorTheme__listItem',
        listitemChecked: 'TypixEditorTheme__listItemChecked',
        listitemUnchecked: 'TypixEditorTheme__listItemUnchecked',
        nested: {
            listitem: 'TypixEditorTheme__nestedListItem',
        },
        olDepth: [
            'TypixEditorTheme__ol1',
            'TypixEditorTheme__ol2',
            'TypixEditorTheme__ol3',
            'TypixEditorTheme__ol4',
            'TypixEditorTheme__ol5',
        ],
        ul: 'TypixEditorTheme__ul',
    },
    mark: 'TypixEditorTheme__mark',
    markOverlap: 'TypixEditorTheme__markOverlap',
    paragraph: 'TypixEditorTheme__paragraph',
    quote: 'TypixEditorTheme__quote',
    specialText: 'TypixEditorTheme__specialText',
    tab: 'TypixEditorTheme__tabNode',
    table: 'TypixEditorTheme__table',
    tableAddColumns: 'TypixEditorTheme__tableAddColumns',
    tableAddRows: 'TypixEditorTheme__tableAddRows',
    tableAlignment: {
        center: 'TypixEditorTheme__tableAlignmentCenter',
        right: 'TypixEditorTheme__tableAlignmentRight',
    },
    tableCell: 'TypixEditorTheme__tableCell',
    tableCellActionButton: 'TypixEditorTheme__tableCellActionButton',
    tableCellActionButtonContainer:
        'TypixEditorTheme__tableCellActionButtonContainer',
    tableCellHeader: 'TypixEditorTheme__tableCellHeader',
    tableCellResizer: 'TypixEditorTheme__tableCellResizer',
    tableCellSelected: 'TypixEditorTheme__tableCellSelected',
    tableFrozenColumn: 'TypixEditorTheme__tableFrozenColumn',
    tableFrozenRow: 'TypixEditorTheme__tableFrozenRow',
    tableRowStriping: 'TypixEditorTheme__tableRowStriping',
    tableScrollableWrapper: 'TypixEditorTheme__tableScrollableWrapper',
    tableSelected: 'TypixEditorTheme__tableSelected',
    tableSelection: 'TypixEditorTheme__tableSelection',
    text: {
        bold: 'TypixEditorTheme__textBold',
        capitalize: 'TypixEditorTheme__textCapitalize',
        code: 'TypixEditorTheme__textCode',
        highlight: 'TypixEditorTheme__textHighlight',
        italic: 'TypixEditorTheme__textItalic',
        lowercase: 'TypixEditorTheme__textLowercase',
        strikethrough: 'TypixEditorTheme__textStrikethrough',
        subscript: 'TypixEditorTheme__textSubscript',
        superscript: 'TypixEditorTheme__textSuperscript',
        underline: 'TypixEditorTheme__textUnderline',
        underlineStrikethrough: 'TypixEditorTheme__textUnderlineStrikethrough',
        uppercase: 'TypixEditorTheme__textUppercase',
    },
};

export default defaultTheme;