export const EditorTheme: any = { //TODO: remove any after updating @typix-editor/react package
    autocomplete: "typix-autocomplete",
    blockCursor: "typix-block-cursor",
    characterLimit: "typix-character-limit",
    code: "typix-code",
    codeHighlight: {
        atrule: "typix-token--attr",
        attr: "typix-token--attr",
        boolean: "typix-token--property",
        builtin: "typix-token--selector",
        cdata: "typix-token--comment",
        char: "typix-token--selector",
        class: "typix-token--function",
        "class-name": "typix-token--function",
        comment: "typix-token--comment",
        constant: "typix-token--property",
        deleted: "typix-token--deleted",
        doctype: "typix-token--comment",
        entity: "typix-token--operator",
        function: "typix-token--function",
        important: "typix-token--variable",
        inserted: "typix-token--inserted",
        keyword: "typix-token--attr",
        namespace: "typix-token--variable",
        number: "typix-token--property",
        operator: "typix-token--operator",
        prolog: "typix-token--comment",
        property: "typix-token--property",
        punctuation: "typix-token--punctuation",
        regex: "typix-token--variable",
        selector: "typix-token--selector",
        string: "typix-token--selector",
        symbol: "typix-token--property",
        tag: "typix-token--property",
        unchanged: "typix-token--unchanged",
        url: "typix-token--operator",
        variable: "typix-token--variable",
    },
    embedBlock: {
        base: "typix-embed-block",
        focus: "typix-embed-block--focus",
    },
    hashtag: "typix-hashtag",
    heading: {
        h1: "typix-heading--h1",
        h2: "typix-heading--h2",
        h3: "typix-heading--h3",
        h4: "typix-heading--h4",
        h5: "typix-heading--h5",
        h6: "typix-heading--h6",
    },
    hr: "typix-hr",
    hrSelected: "typix-hr--selected",
    image: "typix-image",
    indent: "typix-indent",
    layoutContainer: "typix-layout-container",
    layoutItem: "typix-layout-item",
    link: "typix-link",
    list: {
        checklist: "typix-checklist",
        listitem: "typix-list__item",
        listitemChecked: "typix-list__item--checked",
        listitemUnchecked: "typix-list__item--unchecked",
        nested: {
            listitem: "typix-list__item--nested",
        },
        olDepth: [
            "typix-list--ol1",
            "typix-list--ol2",
            "typix-list--ol3",
            "typix-list--ol4",
            "typix-list--ol5",
        ],
        ul: "typix-list--ul",
    },
    mark: "typix-mark",
    markOverlap: "typix-mark--overlap",
    paragraph: "typix-paragraph",
    quote: "typix-quote",
    specialText: "typix-special-text",
    tab: "typix-tab",
    table: "typix-table",
    tableAddColumns: "typix-table__add-columns",
    tableAddRows: "typix-table__add-rows",
    tableAlignment: {
        center: "typix-table--align-center",
        right: "typix-table--align-right",
    },
    tableCell: "typix-table__cell",
    tableCellActionButton: "typix-table__cell-action-btn",
    tableCellActionButtonContainer: "typix-table__cell-action-container",
    tableCellHeader: "typix-table__cell--header",
    tableCellResizer: "typix-table__cell-resizer",
    tableCellSelected: "typix-table__cell--selected",
    tableFrozenColumn: "typix-table--frozen-column",
    tableFrozenRow: "typix-table--frozen-row",
    tableRowStriping: "typix-table--row-striping",
    tableScrollableWrapper: "typix-table-scrollable-wrapper",
    tableSelected: "typix-table--selected",
    tableSelection: "typix-table__selection",
    text: {
        bold: "typix-text--bold",
        capitalize: "typix-text--capitalize",
        code: "typix-text--code",
        highlight: "typix-text--highlight",
        italic: "typix-text--italic",
        lowercase: "typix-text--lowercase",
        strikethrough: "typix-text--strikethrough",
        subscript: "typix-text--subscript",
        superscript: "typix-text--superscript",
        underline: "typix-text--underline",
        underlineStrikethrough: "typix-text--underline-strikethrough",
        uppercase: "typix-text--uppercase",
    },
};